# Generated by Django 5.1.3 on 2024-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
